name: actions_auto_run
on:
  push:
  schedule:
    - cron: "00 17  * * * "

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install
      #      run: |
      #            python -m pip install --upgrade pip
      #            pip install -r requirements.txt
      # Runs a set of commands using the runners shell
      - name: run script
        env:
          VARIABLE_JSON: ${{ secrets.VARIABLE_JSON }}
        run: |
          pipenv run python refresh.py
      #        python3 refresh.py

      - name: Commit files
        run: |
          git config --global user.email "maikaiyang@outlook.com"
          git config --global user.name "MaiXiaoMeng"
          git add .
          git commit -m "actions_auto_run 自动上传" -a || exit 0
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
